### ISSUE TITLE
Export library not showing up in the context menu. 

### ISSUE THREAD

**Issue by feralwriter** [ffes/nppsnippets#10]
Right-clicking the combo box where the library appears only gives me an Import Library option. According to the docs here: http://nppsnippets.readthedocs.io/en/latest/libraries.html#importing-and-exporting-libraries I should be able to export. 

![snippet error](https://cloud.githubusercontent.com/assets/22485733/24517770/5caf2f7e-1534-11e7-8808-7c6e442cef67.png)

PS - thanks for an excellent plugin!

**Comment by mikhoul** [comment]
@feralwriter   Just checked and everything is fine on my side: http://i.imgur.com/UgNQ2sD.png

Here's the version I use: http://i.imgur.com/0lzYxfX.png


Regards :octocat:

**Comment by feralwriter** [comment]
Thanks. I will have to poke around further. Here is teh version I am using:

![snippets version](https://cloud.githubusercontent.com/assets/22485733/24520495/89f48b9c-153d-11e7-869e-bdc541da8383.png)

**Comment by ffes** [comment]
@feralwriter You need the latest development build for that. The docs refer to the latest. The docs for the 1.3.0 are not on Read The Docs.

The links on my homepage don't work at the moment and it will take a bit of time to fix them. You can download it from https://www.dropbox.com/s/k2p20lrm8pqr6dx/NppSnippets-2016-12-07-x32.zip?dl=0

Please let me know if exporting works as expected

@mikhoul You are using the latest version

**Comment by feralwriter** [comment]
That worked. Thank you.

**Comment by ffes** [comment]
Just released [v1.4.0](https://github.com/ffes/nppsnippets/releases/tag/v1.4.0).
