### ISSUE TITLE
Dev builds arent working

### ISSUE THREAD

**Issue by vpontin** [ffes/nppsnippets#11]
Hi!

i tried to download the beta x64 build from your website (https://www.fesevur.com/nppsnippets/), but both links gives me a dropbox's 404 error.

Is there any builds for NPP 64 floating around?

**Comment by ffes** [comment]
I am working on a dropbox public folder emulator, that is almost ready for its first release.

For now: here are the download links to the latest development builds.

https://www.dropbox.com/s/k2p20lrm8pqr6dx/NppSnippets-2016-12-07-x32.zip?dl=0
https://www.dropbox.com/s/b4nroy24vo2uj30/NppSnippets-2016-12-07-x64.zip?dl=0

**Comment by chcg** [comment]
Dev builds could be provided on every commit by the usage of appveyor CI. With PR #13 the NppSnippets.dll is available as artifact. That could be extended to provide a complete installation.

**Comment by vpontin** [comment]
@chcg i tried to open the latest build, but when i go to artifacts no matter what job i select the artifacts tab is always empty

**Comment by chcg** [comment]
@vpontin The artifacts of builds older than 3 months are automatically deleted by appveyor, see https://www.appveyor.com/blog/2018/05/24/artifacts-retention-policy/

**Comment by vpontin** [comment]
So any chance to get those old builds?
