### ISSUE TITLE
Runtime error for v.1.4.0

### ISSUE THREAD

**Issue by dkostromin** [ffes/nppsnippets#12]
When I try to add a new entry - I receive the error:
![image](https://user-images.githubusercontent.com/31317191/29674254-4b73a91c-88fa-11e7-8417-6afb09855fea.png)

Do you know the fix or what it the way to solve the issue?

Thanks,
Dmitriy.

**Comment by ffes** [comment]
I need more info.
What "new entry"? A new library or a new snippet?
What fields are filled, what not?

**Comment by dkostromin** [comment]
It is fine already, not sure what was the reason of the issue.
