### ISSUE TITLE
http://download.fesevur.com/snippets-libs/ subdomain not found

### ISSUE THREAD

**Issue by scottrlarson** [ffes/nppsnippets#15]
Thank you for creating this plugin. Is there a possibility to get this subdomain working again? I wanted to download the markdown library.

when I visit http://download.fesevur.com/snippets-libs/markdown-2016-03-04.zip I get an error that subdomain is not found

**Comment by vpontin** [comment]
Already having this issue!

**Comment by 1vanK** [comment]
Maybe someone will share a copy of this file?

**Comment by ffes** [comment]
Links on https://www.fesevur.com/nppsnippets are fixed
