### ISSUE TITLE
During the opening of the resource file NppSnippets_res.rc error coming out

### ISSUE THREAD

**Issue by andrecool-68** [ffes/nppsnippets#23]
I want to edit the size of the forms and I can not do it because of this error. The plugin interface translation into Russian language, the words get larger and don't fit. Please help me to find the cause of this error. Installed Visual Studio 2017

![58 05-48-17-6408](https://user-images.githubusercontent.com/3471892/54881951-f45a6280-4e5d-11e9-9db0-fb85fd6e394c.png)

**Comment by andrecool-68** [comment]
I took the sources of the previous versions of the plugin and opened them in Visual Studio 2015, there is also an error opening the resource file NppSnippets_res.rc

**Comment by andrecool-68** [comment]
What packages do I need to install for Visual Studio to fix this error?

**Comment by ffes** [comment]
That file contains version information based on the current git repo.  

Your will need to build the solution first. The build process creates that file for you. Or you can start `version_git.bat` manually from the projects root directory.

**Comment by ffes** [comment]
AFK right now, but I think the resource editor doesn't like the version info block as it is. I mostly edit them manually.

But you write that you want to increase the size of the dialogs. Could you tell me the reason for this?

**Comment by andrecool-68** [comment]
@ffes 
> Could you tell me the reason for this?

Words in Russian take up more space than English words

**Comment by andrecool-68** [comment]
Manually start the file `version_get.bat`, created a new `version_git.h` file with this content, but now comes out a new error.

`version_git.h`

`#pragma once `
`#define VERSION_GIT_STR "UNKNOWN"` 
`#define VERSION_GIT_WSTR L"UNKNOWN" `

![1](https://user-images.githubusercontent.com/3471892/54909920-f111b600-4ef3-11e9-9cd1-5c8e58e20c77.png)

**Comment by ffes** [comment]
I see this error as well. Not sure why it happens. Looks like an issue with the SDK at first glimpse.

But as I said, I almost always edit the resources manually. Not ideal but the resource editor makes such a mess of the file that I find myself manually copy/paste and adjusting its results

**Comment by ffes** [comment]
Closing this because it seems to be a Visual Studio problem that is beyond my control.
