### ISSUE TITLE
Unable to find the database.  Check your installation.

### ISSUE THREAD

**Issue by BugZappr** [ffes/nppsnippets#24]
When I install Snippets from the new plugin manager, and try to open it (either from the plugin menu, or from the tool button in creates), I get "Unable to find the database.  Check your installation."  I wondered if this might be due to the new directory structure NPP's new Plugin Admin is using; and it is.

If I copy the files from {NPP}\NppSnippets\NppSnippets to the {NPP}\NppSnippets directory, it does find them.  Thus, they are being distributed in the wrong place for the new Plugin Admin, or it is looking in the wrong place.  Should be a simple change, but it needs updating.

**Comment by ffes** [comment]
Dup of #20

**Comment by ffes** [comment]
I will release a new version

**Comment by BugZappr** [comment]
My bad.  I searched issues on the error message, but it didn't come up.  I might have found it yet.
