### ISSUE TITLE
Snippet code with no break line

### ISSUE THREAD

**Issue by gwarah** [ffes/nppsnippets#27]
1. Open a new file (unix format). Create and select this code

```
if [ $a -eq 0 ]; then
    echo "a = 0"
else
    echo "a != 0"
fi 
```

2. Try to add a new snippet from the selected code. In my environment, it results on this non-formatted code:

`if [ $a -eq 0 ]; then     echo "a = 0"  else     echo "a != 0" fi `

My environment: 

OS: windows 7
npp: 7.8.2
Snippets vs: 1.5.0

**Comment by ffes** [comment]
Great find.

The line ending of the string from the selection or clipboard is not converted to CRLF, what the Windows dialog needs. I'm working on a fix right now.
