### ISSUE TITLE
npp freezing creating a bash snippet

### ISSUE THREAD

**Issue by gwarah** [ffes/nppsnippets#28]
Scenario

1. create a new snippet with these data

![freezing_snippet](https://user-images.githubusercontent.com/5703210/72160164-a424a080-339c-11ea-9849-d7756832acbe.png)

After pressing ok, npp freezes.

2. I've found a workaround to this problem just filling a dummy code in "before cursor" field:

![workaround](https://user-images.githubusercontent.com/5703210/72160379-febdfc80-339c-11ea-9804-e5397d3ded64.png)

My environment:
OS: windows 7
Npp: 7.8.2
Snippets: 1.5.0

**Comment by ffes** [comment]
This has been fixed in the repository already, but have not yet released a new version.
