### ISSUE TITLE
Export a library

### ISSUE THREAD

**Issue by jntrb** [ffes/nppsnippets#3]
I have created a library. I also see that it is possible to import a library. A file to import would be my choice for distributing my library. However, I can't find a way to export a library to a file which could be imported later.

My feature request is to provide a "Export library..." entry in the context menu of the combobox.

**Comment by crash5** [comment]
Hi,

I think a csv export/import function is better. You can make csv in any text editor, excel, opeoffice calc stb. And sqlite can import/export easily.

**Comment by ffes** [comment]
@crash5 Export to csv is a feature of the command line tool and NppSnippets does not use the command line tool. It uses the C API. So I shall need to write my own parse and writer for csv with all the drawbacks of that. Not having to write those parser is why I use SQLite in the first place.

Therefore I recently started the development of this "Export library" feature. No idea when this will be finished.

But if somebody writes decent csv or other text based format (like sql, json or xml) import and export routines, a PR will always be reviewed.

**Comment by ffes** [comment]
The code to export the current library to a SQLite database that can be imported as well has been merged.
