### ISSUE TITLE
Ideas for shortcut keys

### ISSUE THREAD

**Issue by gwarah** [ffes/nppsnippets#30]
I suggest these shortcut keys: 

1. One that focuses to a search box so that it would more easily select a snippet. Could be also change the focus to the first snippet of the list;

2. Other that focuses to the selecting set of snippets combobox;

3. Another to call the Snippet context menu

![2020_01_npp_github](https://user-images.githubusercontent.com/5703210/72631446-01879700-3933-11ea-98c8-14de29bdc5c1.png)

**Comment by ffes** [comment]
You are actually suggestion two things (shortcut keys and searching) in one issue, which is not great for handling issues. But I like both ideas.

I am gone close this one and create two separate issues.

> Another to call the Snippet context menu

Note that once you are in the list of snippets your can use the [context menu key](https://en.wikipedia.org/wiki/Menu_key) or `Shift+F10` to open the context menu. This is standard Windows behavior.

**Comment by gwarah** [comment]
> I am gone close this one and create two separate issues.
Ok, of course! It's fine at this way! 

> Note that once you are in the list of snippets your can use the context menu key or Shift+F10 to open the context menu. This is standard Windows behavior.

Yes, indeed, but configuring one shortcut key to change the focus to snippets frame and open the context menu in one action I believe is the best way to quickly create snipptes when the developer is writing codes.
