### ISSUE TITLE
Shortcut keys to navigate the snippets panel

### ISSUE THREAD

**Issue by ffes** [ffes/nppsnippets#31]
As suggested by @gwarah in #30 

He suggest a shortcut key to focus the list of snippets and a shortcut key to focus the combo to select the library.

To make that possible the Snippets-menu in the Plugin menu needs to get to actions to focus those items. Then it is up to the user to add their own favorite shortcut key with the shortcut keys dialog of N++

**Comment by gwarah** [comment]
There are two use important use cases to analyze this issue:

1. User wants to get a stored snippet: in my opinion is exactly as you've described:

> He suggest a shortcut key to focus the list of snippets and a shortcut key to focus the combo to select the library.  

2. User wants to save a selected code as a snippet: in such cases I suggest (if possible) a new shortcut that performs 2 actions: change the focus to snippet frame and then open the context menu, or in the npp menu context, insert a option this option.  Maybe this case also will require one more issue.
