### ISSUE TITLE
Search the list of snippets

### ISSUE THREAD

**Issue by ffes** [ffes/nppsnippets#32]
As suggested by @gwarah in #30 

Add a search box at the top of the list of snippets. Also see his mock-up in #30

There are two ways this can be done:
* Filtering the list as you type. This could become slow. It probably requires reloading all the data after every keystroke.
* Select the first appearance of the found item in the list.

Not sure what is better at this point.

**Comment by gwarah** [comment]
I believe the first option is better. As user type the list filters the options according the text.  

Suggest also that during the text typing at any moment after [tab] will be pressed, the first option filtered in the list will focused.

**Comment by ffes** [comment]
A dll that includes this feature can be downloaded from GitHub Actions.
At this moment the most recent build is: https://github.com/ffes/nppsnippets/actions/runs/307122959

**Comment by ffes** [comment]
This feature has been in the repo for almost half a year now. Closing this issue.
