### ISSUE TITLE
Use autocomplete/tab key to insert a snippet just by typing its name and then pressing TAB

### ISSUE THREAD

**Issue by astrohart** [ffes/nppsnippets#34]
Visual Studio has a snippet functionality (along with alot of other IDEs I suspect) where you type text that is the same as the name of the snippet, and then just press TAB.  Then the snippet name is replaced with the snippet content for you.

I am lazy -- I want to type my code out and not have to lift my fingers from the keyboard, click the jigsaw button to open the Snippets panel, and then find and double click the snippet name and then go back to typing.

Would be nice to implement this standard feature that is available out of the box in IDEs.

**Comment by ffes** [comment]
Really a dup of #33, that I will reopen.
