### ISSUE TITLE
in modern browser (EDGE) html template snippet force browser to use browser style.

### ISSUE THREAD

**Issue by tst32** [ffes/nppsnippets#35]
It is not really a bug, but EDGE force browser styles over mines so i ended with editing template as follow `<!DOCTYPE html>
<html lang="en"> ` 
@ffes thanks for your plugin

**Comment by ffes** [comment]
I'm not sure what you mean. As far as I know MS Edge is just another Chromium based browser. I don't see how that relates to the plugin.

Do you think a template should be adjusted? If so, which template, what should it become and why?

Please provide more information.

**Comment by tst32** [comment]
I did the correction as follow
![image](https://user-images.githubusercontent.com/23115742/114360474-be3fc680-9b7d-11eb-90fb-2fc2a4d1e93f.png)
that works for me with edge 89.0.774.75

**Comment by ffes** [comment]
Now I see that the HTML template in the template database still has HTML4 / XHTML styled doctype. In my own database I also have changed that. I will update the template database as well.

Thanks for spotting this.

**Comment by ffes** [comment]
An off-topic question. What is the plugin that you have on the left?

**Comment by tst32** [comment]
this is a notepadplusplus feature. 
![image](https://user-images.githubusercontent.com/23115742/115863825-b0702800-a43e-11eb-9005-704de0330721.png)
