### ISSUE TITLE
Import library function not working on NPP portable.

### ISSUE THREAD

**Issue by propellerhed** [ffes/nppsnippets#36]
Is there a workaround as I would like to sync my custom libraries between desktop and USB stick.

**Comment by ffes** [comment]
Could you please be more specific. "Not working" is impossible to debug.

The workaround is to specify where the database is stored. See https://nppsnippets.readthedocs.io/en/latest/options.html

**Comment by propellerhed** [comment]
I have created a library of powershell snippets in my npp on the desktop and exported them. When I try to import into the portable it appears to be imported but doesn't show up, even after a restart of the portable. I was wondering if there was a config / reg entry I am missing.

**Comment by ffes** [comment]
I'm not sure why this happens. I can't imaging it has anything to do with N++ portable. I think there is something in the import or export that causes this to happen. I think the library gets imported, but becomes invisible for some reason.

If you are familiar with SQL you could peek into the exported library to see if is something strange is happening there. Note that the [database is documented](https://nppsnippets.readthedocs.io/en/latest/database.html).

If not, could you attach the exported SQLite database to this issue? Or else find my email address on [my website](https://www.fesevur.com/about/).

**Comment by ffes** [comment]
No response from the user. Closing this issue.
