### ISSUE TITLE
Issue / proposal for snippets

### ISSUE THREAD

**Issue by dev-masta** [ffes/nppsnippets#4]
I really like your plugin, thank you very much for your work.

But I have issue with using them.
It's not actually an issue, since I suppose everything works exactly as you imagined it, it's more like a proposal.

Example:
Let's say I select a part of code, and want to wrap a div around it.
I choose HTML Tags / Block - Division. It works fine.
But, the added div has class and id set as "?"

Could I please propose that those quotes be empty ? :)

That way I don't need to change them immediately, I can continue with work and get back to it later (maybe go and check how this looks in a browser).
With those question marks I can't, or I will get an error.

I hope you understand me.

more html tags in your plugin put ? inside "", for example Form - Text put ? for value and id, but then we have name="" <-- which is exactly what I would like for every tag
except Anchor - Text and Image, should have href="#" (not empty quotes)

This is something I would like to see very very much, it would improve my experience with your plugin for at least 300%, if not more.

I hope you will see my proposal as useful for others too.

Much obliged, Andre

**Comment by ffes** [comment]
Thanks for the suggestion. I will update the snippets of the template database for the next release.

But you don't have to wait for that. You can easily edit your own snippets. Just right click the entry in the list. And know that editing your snippets has no effect on the snippets of an upgrade. The template database is only used at first install.

**Comment by dev-masta** [comment]
Oh, oh, oh! Silly me, never realized I could edit snippets...

This is even more that I asked for, you were 2 steps ahead of me this whole time.

Hat to the ground man, hat to the ground.

**Comment by ffes** [comment]
And know that you can add/edit/delete libraries as well. Right-click the combo with the name of library.

I just updated my personal database to reflect the changes you suggested. I will update the template database in this repo any time soon. Once committed I will close this issue.

I am working on an export library function, but that is not finished yet. So if you have libraries that could be interesting for other users as well, please let know. I want to create a page when users can download separate libraries.

**Comment by Korb** [comment]
> Let's say I select a part of code, and want to wrap a div around it.

Do I understand correctly that NppSnippets allows to wrap a selected code fragment with a previously saved snippet, inserting the first half of the snippet **before** the selected code fragment, and the second half of the snippet immediately **after** the selected fragment? That is, in essence, to implement the feature available in [the Edit browser add-on](https://addons.mozilla.org/en-GB/firefox/addon/edit/).

If this feature is missing, does it make sense for me to create a separate issue for it? Your Notepad++ extension is most suitable for this functionality.

Upd. like [applying surround live templates﻿](https://www.jetbrains.com/help/phpstorm/wrapping-a-tag-example-of-applying-surround-live-templates.html) at PhpStorm.
