### ISSUE TITLE
a hook to get non-database snippets

### ISSUE THREAD

**Issue by Deadooshka** [ffes/nppsnippets#46]
It would be useful to add the ability to inject some script or cli-command that output snippets from another sources e.g. in json format.

**Comment by ffes** [comment]
To import multiple snippets you can use add them directly to the database. See https://nppsnippets.readthedocs.io/en/latest/database.html for more information.

I have no plans to add any other import option. That is too time consuming to build and maintain and I don't have a personal interest in that, but a decent PR will by looked at obviously.

Sorry, but I closing this one as "won't fix".
