### ISSUE TITLE
Instructions for manual installtion

### ISSUE THREAD

**Issue by kiwichick888** [ffes/nppsnippets#50]
The instructions on the Snippets homepage say: To install manually copy NppSnippets.dll to the plugins/NppSnippets directory, copy NppSnippets.sqlite to the plugins/Config directory.

However:
1) you don't say what to do with the other files - Languages.sql and Template.sqlite.
2) there is no such file as NppSnippets.sqlite in the zip archive, so do you actually mean NppSnippets.sql?

**Comment by ffes** [comment]
You're right, that is not complete. I saw as well that instructions in the docs is also not accurate enough. I will fix both.

To answer your questions
1. The `*.sql` files are there as a reference.
2. It should be `Template.sqlite`.
