### ISSUE TITLE
Homepage URL is Broken

### ISSUE THREAD

**Issue by dembeck** [ffes/nppsnippets#52]
# ISSUE

In the description for Snippets as shown in the Plugins Admin, there is a URL given `https://www.fesevur.com/nppsnippet` for the "Homepage".

If you go to that page, you get the message `Page not found`

The rest of your site seems to work, just not that page.

# SCREENSHOTS

- **URL as shown in Notepad++**

<img width="565" alt="image" src="https://user-images.githubusercontent.com/9568447/211585169-9eba1ca5-49dc-4d7a-ac2a-5be90e60d48a.png">

---

- **Site with error message.**

<img width="977" alt="image" src="https://user-images.githubusercontent.com/9568447/211584976-b2b17758-305e-47de-8c92-e72ce4019769.png">

**Comment by ffes** [comment]
You misspelled the URL. There is an `s` missing at the end.
