### ISSUE TITLE
add For loop in snipet 

### ISSUE THREAD

**Issue by HelloWorldFR** [ffes/nppsnippets#54]
Hello,
we can add for and forech loop and 

`for($i=0;$i<`

`;$i++){
// Type your code here
}`

Best regard

**Comment by ffes** [comment]
Did you read the docs?

https://nppsnippets.readthedocs.io/en/latest/usage.html#edit-a-snippet

**Comment by HelloWorldFR** [comment]
Its ok , thanks :)

**Comment by ffes** [comment]
Based on your comment I close the issue
