### ISSUE TITLE
[Feature request] Variables to auto resolve on insert

### ISSUE THREAD

**Issue by Clicketyclick** [ffes/nppsnippets#65]
Being a insert variables in snippet which will auto resolve in insert.

Like:
```diff
- Date: ${DATE}
+ Date: 2024-07-04T14:14:00
```

I've nicked this list from DoxyIT:

Keywords:

Variable| FUNCTION
---|---
$FILENAME	| The current file name.
$FUNCTION	| The name of the function/method.
$PARAM	| Expands to a single function/method parameter. Any line containing this will get repeated for each parameter.
$COMPUTER	| Current computer name.
$USER	| User account name of current user.
$FULLUSER	| full user name of current user.
$DATE	| Current date and time, format ISO 8601.
$DATE_a	| Abbreviated weekday name
$DATE_A	| Full weekday name
$DATE_b	| Abbreviated month name
$DATE_B	| Full month name
$DATE_c	| Date and time representation appropriate for locale
$DATE_d	| Day of month as decimal number (01	| 31)
$DATE_H	| Hour in 24	| hour format (00	| 23)
$DATE_I	| Hour in 12	| hour format (01	| 12)
$DATE_j	| Day of year as decimal number (001	| 366)
$DATE_m	| Month as decimal number (01	| 12)
$DATE_M	| Minute as decimal number (00	| 59)
$DATE_p	| Current locale's A.M./P.M. indicator for 12-hour clock
$DATE_S	| Second as decimal number (00	| 59)
$DATE_U	| Week of year as decimal number, with Sunday as first day of week (00	| 53)
$DATE_w	| Weekday as decimal number (0	| 6; Sunday is 0)
$DATE_W	| Week of year as decimal number, with Monday as first day of week (00	| 53)
$DATE_x	| Date representation for current locale
$DATE_X	| Time representation for current locale
$DATE_y	| Year without century, as decimal number (00	| 99)
$DATE_Y	| Year with century, as decimal number
$DATE_z, $DATE_Z	| Either the time	| zone name or time zone abbreviation, depending on registry settings; no characters if time zone is unknown
$@	| Expands to the prefix character for Doxygen commands.
$|	| Marks the alignment position. This is only valid for lines containing $PARAM.

**Comment by ffes** [comment]
There are already three menu items in the `Edit` menu of Notepad++ to insert the date and you can change the `Date Time (customized)` in the settings. The filename (in various forms) can already be copied to the clipboard quite easily, by right clicking the tab.

I don't see any need to add this to the Snippets plugin. But if someone implements it, I will review a pull request.

**Comment by Clicketyclick** [comment]
This is merely a clarification of:

- [Real template handling](https://nppsnippets.readthedocs.io/en/latest/wishlist.html): variables in the snippets}

NOT just a date function.

I currently use DoxyIT for inserting a function block like:
```php
/**
 *  @fn       	$FUNCTION
 *  @brief      $(Brief description)
 *  
 *  @param [in] $PARAM $|$(Description for $PARAM)
 *  @return     $(Return description)
 *  
 *  @details    $(More details)
 *  
 *  @example   
 *  
 *  @todo      
 *  @bug       
 *  @warning   
 *  
 *  @see        https://
 *  @since      ${DATE} / ${USER}
 */
function myFunction($abc, $defg)
{
}	// myFunction()

//----------------------------------------------------------------------
```

Variables would make Snippet so much more flexible.
