### ISSUE TITLE
Empty line at beginning of snippet

### ISSUE THREAD

**Issue by stihl716** [ffes/nppsnippets#8]
I was writing a new snippet today and wanted to leave several blank lines at the beginning.  However, when I clicked the OK button to save the snippet I got this message:

Before Selection needs to be entered!

Was a bit confused because there was text in the Before Section.  

I deleted the blank lines and was then able to save the snippet.

Great plugin!  I use it all the time.  Thanks for making it!

dp

**Comment by ffes** [comment]
Thanks for the report. This bug has been fixed in the repo. See http://nppsnippets.readthedocs.org/en/latest/history.html

Note to self: I really need to release 1.4

**Comment by ffes** [comment]
If you want to test this new version, you can find a test build at http://downloads.fesevur.com/builds/NppSnippets-2016-03-30.zip

Note that this dll still has the version number 1.3.0, but it is the most recent version. I still have to find a way to distinguish development builds from releases.
