### ISSUE TITLE
when an x64 version will be available?

### ISSUE THREAD

**Issue by grosgean** [ffes/nppsnippets#9]

**Comment by ffes** [comment]
The Visual Studio project file already support the x64 platform. You can build it yourself, if you are familiar with VS. I will provide a development build of x64 any time soon.

A x64 release takes a bit longer because the plugin manager doesn't support x64 (fully?) yet

**Comment by grosgean** [comment]
I can try, but I have no much experience with that. Anyway, your plugin is very useful, and it is great you're planning to develop it further!

**Comment by grosgean** [comment]
I did it and it works. I noticed when I change files with different languages of my progect it takes 2-3 seconds delay when plugin load snippets for this language (for example HTML to PHP)

**Comment by ffes** [comment]
Just added the latest development builds (including a x64) to my site https://www.fesevur.com/nppsnippets

**Comment by ffes** [comment]
> I noticed when I change files with different languages of my progect it takes 2-3 seconds delay when plugin load snippets for this language (for example HTML to PHP).

I don't see this happen. If the problem keeps recurring, please open a new issue.

**Comment by grosgean** [comment]
I found the problem. It was because of plugins data was not in the Application Data but in the same folder with npp and NppSnippets.sqlite appeared readonly. It also crushed when I attempted to add or edit snippet. Now I copied it and it works just fine!

**Comment by ffes** [comment]
Thanks for the feedback. I will extend the note about not placing the db in AppData in the docs with this remark.

**Comment by dartraiden** [comment]
Hello. Development build links are broken. Can you reupload it or upload on GitHub?

**Comment by ffes** [comment]
Just released [v1.4.0](https://github.com/ffes/nppsnippets/releases/tag/v1.4.0). It includes a x64 build of the plugin. I will update my website and N++ plugin manager in the coming days.
